# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.dialects.postgresql import *

db = create_engine("postgres://postgres:hackme@localhost/uoit")
metadata = MetaData(bind=db)

courses =  Table('courses', metadata, autoload=True)
schedules =  Table('schedules', metadata, autoload=True)
instructors =  Table('instructors', metadata, autoload=True)
sections =  Table('sections', metadata, autoload=True)
teaches =  Table('teaches', metadata, autoload=True)